language: python
jdk:
  - oraclejdk7 
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: "python setup.py install"
script: nosetests -s
env:
  - NEO4J_VERSION="2.1.5"
before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
