language: python
jdk:
  - oraclejdk7 
python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
install: "python setup.py install"
script: nosetests -s
env:
  - NEO4J_VERSION="2.0.1"
  - NEO4J_VERSION="2.0.4"
  - NEO4J_VERSION="2.1.8"
  - NEO4J_VERSION="2.2.5"
before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - sed -i.bak 's/auth_enabled=true/auth_enabled=false/' neo4j-community-2.2.5/conf/neo4j-server.properties
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
